"""Compute cost-per-audio-minute across hardware platforms.

Combines measured RTF (from runs/results.jsonl) with hourly compute cost
to produce the headline economic metric: $ per minute of audio transcribed.

Cost model:
    cost_per_audio_minute = (RTF * hourly_$) / 60

Hetzner numbers are projected from GCP's RTF until we benchmark on actual
Hetzner hardware. Set `--measured` to use measured-only rows.

Usage:
    python -m src.cost_per_min                   # write paper/COST.md
    python -m src.cost_per_min --measured        # only measured cells
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Hourly compute prices ($/hr) per platform label.
PLATFORM_HOURLY_USD: dict[str, float] = {
    "gcp-c3-standard-8": 0.40,
    "hetzner-cx22": 0.008,
    "hetzner-cax11": 0.009,
    "hetzner-cx53": 0.043,
    "hetzner-ccx53": 0.214,
}

# Projected RTF multiplier vs gcp-c3-standard-8 when we don't have measurements yet.
# Empirical scaling has been ~ #cores reciprocal × 0.7 efficiency penalty.
PROJECTED_RTF_SCALE: dict[str, float] = {
    "gcp-c3-standard-8": 1.0,
    "hetzner-cx22": 3.0,    # 2 cores, x86 — 3× slower than 8-core c3
    "hetzner-cax11": 3.5,   # 2 cores ARM Ampere — slightly more for x86-built CT2
    "hetzner-cx53": 0.6,    # 16 cores, AMD Zen — faster than c3 on memory-bound steps
    "hetzner-ccx53": 0.55,  # 16 dedicated cores
}


def _root(name: str) -> str:
    n = name.replace("zero-shot-", "")
    for s in ("-hf", "-openai", "-cpp"):
        n = n.replace(s, "")
    return "turbo" if n == "large-v3-turbo" else n


def _backend(row: dict) -> str:
    return row.get("extra", {}).get("backend", "ct2-faster-whisper")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--results", default="runs/results.jsonl", type=Path)
    p.add_argument("--out", default="paper/COST.md", type=Path)
    p.add_argument("--measured", action="store_true",
                   help="show only platforms with measured cells (skip projections)")
    args = p.parse_args()

    rows = [json.loads(l) for l in args.results.open() if l.strip()]
    measured = {r["platform_label"] for r in rows}

    msa = [r for r in rows if r.get("dialect") == "msa"
           and r.get("n_samples") in (50, 100)]

    lines: list[str] = [
        "# Cost per audio minute",
        "",
        "_Auto-generated by `python -m src.cost_per_min`. "
        "$/audio-minute = (RTF × hourly_$) / 60._",
        "",
        f"Measured platforms: {sorted(measured)}.",
        "Projections marked `(proj)` use a scaling factor vs gcp-c3-standard-8.",
        "",
        "## Hourly rates",
        "",
        "| platform | $/hr | RTF scale (vs c3-standard-8) |",
        "|---|---:|---:|",
    ]
    for plat, hr in PLATFORM_HOURLY_USD.items():
        scale = PROJECTED_RTF_SCALE.get(plat, 1.0)
        lines.append(f"| {plat} | {hr:.3f} | ×{scale:.2f} |")
    lines.append("")

    # Best CT2 int8 cell per model size
    by_model: dict[str, dict] = {}
    for r in msa:
        if _backend(r) != "ct2-faster-whisper":
            continue
        if r["config"]["compute_type"] != "int8":
            continue
        m = _root(r["config"]["model_name"])
        if m not in by_model or r["wer"] < by_model[m]["wer"]:
            by_model[m] = r

    lines += [
        "## CT2 int8 — recommended production backend (MSA, beam=1, threads=4)",
        "",
        "| model | WER% | RTF (c3) | platform | RTF (eff) | $/audio-min | $/audio-hr |",
        "|---|---:|---:|---|---:|---:|---:|",
    ]
    for m in ["tiny", "base", "small", "medium", "turbo", "large-v3"]:
        if m not in by_model:
            continue
        r = by_model[m]
        rtf_c3 = r["rtf"]
        wer = r["wer"] * 100
        for plat, hr in PLATFORM_HOURLY_USD.items():
            if args.measured and plat not in measured:
                continue
            scale = PROJECTED_RTF_SCALE.get(plat, 1.0)
            rtf_eff = rtf_c3 * scale
            cost_min = (rtf_eff * hr) / 60.0
            cost_hr = rtf_eff * hr
            tag = "" if plat in measured else " *(proj)*"
            lines.append(
                f"| {m} | {wer:.1f} | {rtf_c3:.3f} | "
                f"{plat}{tag} | {rtf_eff:.3f} | ${cost_min:.5f} | ${cost_hr:.4f} |"
            )
        lines.append("|||||||| ")
    lines.append("")

    # Cross-backend comparison at the recommended turbo cell
    lines += [
        "## Cross-backend cost comparison at large-v3-turbo MSA",
        "",
        "| backend | quant | WER% | RTF (c3) | $/audio-min on CX22 (proj) | $/audio-min on c3-standard-8 |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for r in msa:
        if _root(r["config"]["model_name"]) != "turbo":
            continue
        be = _backend(r)
        q = r["config"]["compute_type"]
        rtf = r["rtf"]
        wer = r["wer"] * 100
        cx22 = (rtf * PROJECTED_RTF_SCALE["hetzner-cx22"]
                * PLATFORM_HOURLY_USD["hetzner-cx22"]) / 60
        c3 = (rtf * PLATFORM_HOURLY_USD["gcp-c3-standard-8"]) / 60
        lines.append(
            f"| {be} | {q} | {wer:.1f} | {rtf:.3f} | ${cx22:.5f} | ${c3:.5f} |"
        )
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"[ok] wrote {args.out}")


if __name__ == "__main__":
    main()
